project_id = "uspiwwpshkskuqeqfvgc"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-ppv-payment]
verify_jwt = false
